import {
  Zap, Ship, Package, Search, RefreshCw, Truck, ShieldCheck, ArrowRight, Send, CheckCircle, Mail, Shield,
  X, Activity, Anchor, Archive, Award, BarChart, Bell, Book, BookOpen, Box, Briefcase, Building,
  Calculator, Calendar, Camera, Car, Check, ChevronRight, Circle, Clipboard, Clock, Cloud, CloudUpload, Code,
  Coffee, Cog, Coins, Compass, Container, Copy, CreditCard, Crown, Database, Diamond, DollarSign, Download,
  DraftingCompass, Droplet, Earth, Edit, Eye, Factory, File, FileCheck, FileEdit, FileImage, FileText, Film,
  Filter, Fingerprint, Fish, Flag, Flame, Flashlight, Flower, Folder, FolderOpen, Forklift, Gauge, Gift,
  GitBranch, Globe, GraduationCap, Hammer, Handshake, HardDrive, Headphones, Heart, HelpCircle, Home, Image, Import,
  Infinity, Info, InspectionPanel, Key, Keyboard, Lamp, LandPlot, Laptop, Layers, LayoutDashboard, Leaf, Library,
  LifeBuoy, Lightbulb, Link, List, Loader2, Lock, LogOut, Luggage, Magnet, Map, MapPin, Megaphone,
  Menu, MessageCircle, MessageSquare, Mic, Microscope, Monitor, Moon, Mountain, Mouse, Music, Navigation, Newspaper,
  Notebook, PackageCheck, PackageOpen, PaintBucket, Palette, Paperclip, Pause, Pen, PenTool, Pencil, Percent, Phone,
  PiggyBank, Pin, Pizza, Plane, PlaneLanding, PlaneTakeoff, Play, Plug, Plus, Pocket, Podcast, Pointer,
  Popcorn, Power, Printer, Puzzle, QrCode, Quote, Radar, Radio, RadioTower, Receipt, Recycle, Repeat,
  Reply, Rocket, Router, Ruler, Sailboat, Scale, Scan, School, Scissors, Scroll, Server, Settings,
  Shapes, Share, ShoppingBag, ShoppingCart, Siren, Sliders, Smartphone, Smile, Sparkles, Speech, Square, Stamp,
  Star, Store, Sun, Sunrise, Sunset, SwatchBook, Table, Tag, Tags, Target, Tent, Terminal,
  TestTube, Text, TextSearch, Theater, Thermometer, ThumbsUp, Ticket, Timer, ToggleLeft, ToggleRight, TowerControl, ToyBrick,
  Train, TrainTrack, Trash, TreePine, Trees, Trophy, Tv, Umbrella, Unplug, User, UserCheck, UserCog,
  UserPlus, Users, UtensilsCrossed, Vault, Verified, Video, VideoOff, View, Voicemail, Volume2, Wallet, Wand,
  Warehouse, Watch, Waves, Webcam, Wifi, Wind, Wine, Wrench, XCircle, Youtube, ZoomIn, ZoomOut,
  Ban, BarChartHorizontal, Battery, Bed, Beer, Bluetooth, Bone, Bookmark, Bot, Bug, Cable, Cake,
  CarFront, CassetteTape, Cat, ChartArea, ChartBar, ChartLine, ChartPie, ChefHat, Cherry, ChevronDown, ChevronUp, Chrome,
  CircleUser, Clover, Cookie, Crop, Cross, CupSoda, Cpu, Cylinder, Dessert, Dices, Disc, Dog,
  DoorOpen, Drill, Drum, Ear, Egg, EthernetPort, Fan, FastForward, Feather, Fence, FerrisWheel, FireExtinguisher,
  FishingHook, Footprints, Frown, Fuel, Gamepad, Gem, Ghost, GlassWater, Glasses, Goal, Grape, Grip,
  Guitar, Hamburger, Hand, HandCoins, HardHat, Hash, Haze, Hd, Heading, Heater, Helicopter, Highlighter,
  History, Hop, Hospital, Hourglass, IceCream, IceCreamCone, Joystick, Kayak, Landmark, Languages, Lasso, Laugh,
  LeafyGreen, Lectern, LetterText, Ligature, LineChart, Linkedin, LogIn, Logs, Lollipop, Mars, Martini, Medal,
  MemoryStick, Merge, Microwave, Milestone, Milk, Minimize, MonitorDot, MoonStar, Move, Network, Nut, Octagon,
  Omega, Option, Orbit, Origami, Outdent, PaintRoller, Palmtree, Panda, PartyPopper, PawPrint, PcCase, Pentagon,
  PersonStanding, Pi, Piano, PictureInPicture, Pill, Pipette, PlusCircle, Popsicle, PoundSterling, Presentation, Projector, Pyramid,
  Rabbit, Radiation, Radical, Radius, Rainbow, Rat, RectangleHorizontal, RectangleVertical, Ribbon, RockingChair, RollerCoaster, Rose,
  Route, Rss, Satellite, SatelliteDish, Scooter, ScreenShare, SearchX, Section, SendHorizontal, Settings2, Share2, Sheet,
  Shell, ShieldOff, ShipWheel, Shirt, Shovel, ShowerHead, Shrimp, Shrub, Shuffle, Signal, Signature, Signpost,
  SkipBack, SkipForward, Skull, Slack, Slash, Slice, Snail, Snowflake, Sofa, SolarPanel, SortAsc, SortDesc,
  Soup, Space, Spade, Sparkle, Speaker, Spline, Split, SprayCan, Sprout, SquareStack, Squircle, Squirrel,
  StarHalf, StarOff, StepBack, StepForward, Stethoscope, Sticker, StickyNote, StopCircle, StretchHorizontal, StretchVertical, Strikethrough, Subscript,
  Subtitles, SunDim, SunMedium, SunMoon, Superscript, SwissFranc, Sword, Swords, Syringe, Tablets, Tally1, Tally2,
  Tally3, Tally4, Tally5, Tangent, Telescope, TentTree, TestTubes, TextCursor, TextQuote, TicketCheck, TicketPercent, TicketPlus,
  Toilet, Tornado, Torus, Touchpad, Tractor, TrafficCone, TramFront, Transgender, TrendingDown, TrendingUp, Triangle, TruckElectric,
  Turntable, Turtle, TvMinimal, Twitch, Twitter, Type, UmbrellaOff, Underline, Undo, Ungroup, University, Unlink,
  Unlock, Upload, Usb, UserMinus, UserX, Utensils, Van, Variable, VectorSquare, Vegan, VenetianMask, Venus,
  Vibrate, Videotape, Volleyball, Volume, Volume1, VolumeX, Vote, WalletMinimal, Wallpaper, WandSparkles, WashingMachine, Waypoints,
  Webhook, Wheat, WholeWord, WineOff, Workflow, WrapText, ZapOff,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  Zap, Ship, Package, Search, RefreshCw, Truck, ShieldCheck, ArrowRight, Send, CheckCircle,
  Mail, Shield, X, Activity, Anchor, Archive, Award, BarChart, Bell, Book,
  BookOpen, Box, Briefcase, Building, Calculator, Calendar, Camera, Car, Check, ChevronRight,
  Circle, Clipboard, Clock, Cloud, CloudUpload, Code, Coffee, Cog, Coins, Compass,
  Container, Copy, CreditCard, Crown, Database, Diamond, DollarSign, Download, DraftingCompass, Droplet,
  Earth, Edit, Eye, Factory, File, FileCheck, FileEdit, FileImage, FileText, Film,
  Filter, Fingerprint, Fish, Flag, Flame, Flashlight, Flower, Folder, FolderOpen, Forklift,
  Gauge, Gift, GitBranch, Globe, GraduationCap, Hammer, Handshake, HardDrive, Headphones, Heart,
  HelpCircle, Home, Image, Import, Infinity, Info, InspectionPanel, Key, Keyboard, Lamp,
  LandPlot, Laptop, Layers, LayoutDashboard, Leaf, Library, LifeBuoy, Lightbulb, Link, List,
  Loader2, Lock, LogOut, Luggage, Magnet, Map, MapPin, Megaphone, Menu, MessageCircle,
  MessageSquare, Mic, Microscope, Monitor, Moon, Mountain, Mouse, Music, Navigation, Newspaper,
  Notebook, PackageCheck, PackageOpen, PaintBucket, Palette, Paperclip, Pause, Pen, PenTool, Pencil,
  Percent, Phone, PiggyBank, Pin, Pizza, Plane, PlaneLanding, PlaneTakeoff, Play, Plug,
  Plus, Pocket, Podcast, Pointer, Popcorn, Power, Printer, Puzzle, QrCode, Quote,
  Radar, Radio, RadioTower, Receipt, Recycle, Repeat, Reply, Rocket, Router, Ruler,
  Sailboat, Scale, Scan, School, Scissors, Scroll, Server, Settings, Shapes, Share,
  ShoppingBag, ShoppingCart, Siren, Sliders, Smartphone, Smile, Sparkles, Speech, Square, Stamp,
  Star, Store, Sun, Sunrise, Sunset, SwatchBook, Table, Tag, Tags, Target,
  Tent, Terminal, TestTube, Text, TextSearch, Theater, Thermometer, ThumbsUp, Ticket, Timer,
  ToggleLeft, ToggleRight, TowerControl, ToyBrick, Train, TrainTrack, Trash, TreePine, Trees, Trophy,
  Tv, Umbrella, Unplug, User, UserCheck, UserCog, UserPlus, Users, UtensilsCrossed, Vault,
  Verified, Video, VideoOff, View, Voicemail, Volume2, Wallet, Wand, Warehouse, Watch,
  Waves, Webcam, Wifi, Wind, Wine, Wrench, XCircle, Youtube, ZoomIn, ZoomOut,
  Ban, BarChartHorizontal, Battery, Bed, Beer, Bluetooth, Bone, Bookmark, Bot, Bug,
  Cable, Cake, CarFront, CassetteTape, Cat, ChartArea, ChartBar, ChartLine, ChartPie, ChefHat,
  Cherry, ChevronDown, ChevronUp, Chrome, CircleUser, Clover, Cookie, Crop, Cross, CupSoda,
  Cpu, Cylinder, Dessert, Dices, Disc, Dog, DoorOpen, Drill, Drum, Ear,
  Egg, EthernetPort, Fan, FastForward, Feather, Fence, FerrisWheel, FireExtinguisher, FishingHook, Footprints,
  Frown, Fuel, Gamepad, Gem, Ghost, GlassWater, Glasses, Goal, Grape, Grip,
  Guitar, Hamburger, Hand, HandCoins, HardHat, Hash, Haze, Hd, Heading, Heater,
  Helicopter, Highlighter, History, Hop, Hospital, Hourglass, IceCream, IceCreamCone, Joystick, Kayak,
  Landmark, Languages, Lasso, Laugh, LeafyGreen, Lectern, LetterText, Ligature, LineChart, Linkedin,
  LogIn, Logs, Lollipop, Mars, Martini, Medal, MemoryStick, Merge, Microwave, Milestone,
  Milk, Minimize, MonitorDot, MoonStar, Move, Network, Nut, Octagon, Omega, Option,
  Orbit, Origami, Outdent, PaintRoller, Palmtree, Panda, PartyPopper, PawPrint, PcCase, Pentagon,
  PersonStanding, Pi, Piano, PictureInPicture, Pill, Pipette, PlusCircle, Popsicle, PoundSterling, Presentation,
  Projector, Pyramid, Rabbit, Radiation, Radical, Radius, Rainbow, Rat, RectangleHorizontal, RectangleVertical,
  Ribbon, RockingChair, RollerCoaster, Rose, Route, Rss, Satellite, SatelliteDish, Scooter, ScreenShare,
  SearchX, Section, SendHorizontal, Settings2, Share2, Sheet, Shell, ShieldOff, ShipWheel, Shirt,
  Shovel, ShowerHead, Shrimp, Shrub, Shuffle, Signal, Signature, Signpost, SkipBack, SkipForward,
  Skull, Slack, Slash, Slice, Snail, Snowflake, Sofa, SolarPanel, SortAsc, SortDesc,
  Soup, Space, Spade, Sparkle, Speaker, Spline, Split, SprayCan, Sprout, SquareStack,
  Squircle, Squirrel, StarHalf, StarOff, StepBack, StepForward, Stethoscope, Sticker, StickyNote, StopCircle,
  StretchHorizontal, StretchVertical, Strikethrough, Subscript, Subtitles, SunDim, SunMedium, SunMoon, Superscript, SwissFranc,
  Sword, Swords, Syringe, Tablets, Tally1, Tally2, Tally3, Tally4, Tally5, Tangent,
  Telescope, TentTree, TestTubes, TextCursor, TextQuote, TicketCheck, TicketPercent, TicketPlus, Toilet, Tornado,
  Torus, Touchpad, Tractor, TrafficCone, TramFront, Transgender, TrendingDown, TrendingUp, Triangle, TruckElectric,
  Turntable, Turtle, TvMinimal, Twitch, Twitter, Type, UmbrellaOff, Underline, Undo, Ungroup,
  University, Unlink, Unlock, Upload, Usb, UserMinus, UserX, Utensils, Van, Variable,
  VectorSquare, Vegan, VenetianMask, Venus, Vibrate, Videotape, Volleyball, Volume, Volume1, VolumeX,
  Vote, WalletMinimal, Wallpaper, WandSparkles, WashingMachine, Waypoints, Webhook, Wheat, WholeWord, WineOff,
  Workflow, WrapText, ZapOff,
};

export const ICON_NAMES = Object.keys(iconMap);
